version: '3.7'
services:
  db:
    image: mysql:latest
    command: --max-allowed-packet=64M
    restart: always
    environment:
      MYSQL_DATABASE: 'ndms'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: 'newspaper'
    ports:
      - "3306:3306"
volumes: 
  mysql-data: